include:
  - docker-compose.postgres.yml
  - docker-compose.redis.yml

services:
  traefik:
    image: traefik:v3.5
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
      - "6379:6379"
    volumes:
      - ./traefik/config.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/certs:/certs:ro
      - ./traefik/dynamic:/dynamic:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik

networks:
  traefik:
    external: true
