services:
  traefik:
    image: traefik:v3.5
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
      - "6379:6379"
    volumes:
      - ./traefik/config.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/certs:/certs:ro
      - ./traefik/dynamic:/dynamic:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: trustshop
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.postgres.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.postgres.entrypoints=postgres"
      - "traefik.tcp.services.postgres.loadbalancer.server.port=5432"

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.redis.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.redis.entrypoints=redis"
      - "traefik.tcp.services.redis.loadbalancer.server.port=6379"

volumes:
  postgres_data:
  redis_data:

networks:
  traefik:
    external: true
