services:
  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.redis.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.redis.entrypoints=redis"
      - "traefik.tcp.services.redis.loadbalancer.server.port=6379"

volumes:
  redis_data:

networks:
  traefik:
    external: true
